package com.yuen.domain;
// Generated Jan 30, 2018 7:35:01 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QsolutionComponent generated by hbm2java
 */
@Entity
@Table(name = "qsolution_component", catalog = "test")
public class QsolutionComponent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer qsolutionComponentId;
	private Qsolution qsolution;
	private QuestionItem questionItemByCurItemId;
	private QuestionItem questionItemByNextItemId;

	public QsolutionComponent() {
	}

	public QsolutionComponent(Qsolution qsolution, QuestionItem questionItemByCurItemId,
			QuestionItem questionItemByNextItemId) {
		this.qsolution = qsolution;
		this.questionItemByCurItemId = questionItemByCurItemId;
		this.questionItemByNextItemId = questionItemByNextItemId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "qsolution_component_id", unique = true, nullable = false)
	public Integer getQsolutionComponentId() {
		return this.qsolutionComponentId;
	}

	public void setQsolutionComponentId(Integer qsolutionComponentId) {
		this.qsolutionComponentId = qsolutionComponentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qsolution_id")
	public Qsolution getQsolution() {
		return this.qsolution;
	}

	public void setQsolution(Qsolution qsolution) {
		this.qsolution = qsolution;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cur_item_id")
	public QuestionItem getQuestionItemByCurItemId() {
		return this.questionItemByCurItemId;
	}

	public void setQuestionItemByCurItemId(QuestionItem questionItemByCurItemId) {
		this.questionItemByCurItemId = questionItemByCurItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "next_item_id")
	public QuestionItem getQuestionItemByNextItemId() {
		return this.questionItemByNextItemId;
	}

	public void setQuestionItemByNextItemId(QuestionItem questionItemByNextItemId) {
		this.questionItemByNextItemId = questionItemByNextItemId;
	}

}
