package com.yuen.domain;
// Generated Jan 30, 2018 7:35:01 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuestionTypeDict generated by hbm2java
 */
@Entity
@Table(name = "question_type_dict", catalog = "test")
public class QuestionTypeDict implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer questionTypeId;
	private String questionTypeCode;
	private String questionTypeDesc;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<Question> questions_1 = new HashSet<Question>(0);

	public QuestionTypeDict() {
	}

	public QuestionTypeDict(String questionTypeCode, String questionTypeDesc) {
		this.questionTypeCode = questionTypeCode;
		this.questionTypeDesc = questionTypeDesc;
	}

	public QuestionTypeDict(String questionTypeCode, String questionTypeDesc, Set<Question> questions,
			Set<Question> questions_1) {
		this.questionTypeCode = questionTypeCode;
		this.questionTypeDesc = questionTypeDesc;
		this.questions = questions;
		this.questions_1 = questions_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "question_type_id", unique = true, nullable = false)
	public Integer getQuestionTypeId() {
		return this.questionTypeId;
	}

	public void setQuestionTypeId(Integer questionTypeId) {
		this.questionTypeId = questionTypeId;
	}

	@Column(name = "question_type_code", nullable = false, length = 20)
	public String getQuestionTypeCode() {
		return this.questionTypeCode;
	}

	public void setQuestionTypeCode(String questionTypeCode) {
		this.questionTypeCode = questionTypeCode;
	}

	@Column(name = "question_type_desc", nullable = false, length = 65535)
	public String getQuestionTypeDesc() {
		return this.questionTypeDesc;
	}

	public void setQuestionTypeDesc(String questionTypeDesc) {
		this.questionTypeDesc = questionTypeDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionTypeDict")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionTypeDict")
	public Set<Question> getQuestions_1() {
		return this.questions_1;
	}

	public void setQuestions_1(Set<Question> questions_1) {
		this.questions_1 = questions_1;
	}

}
