package com.yuen.domain;
// Generated Jan 30, 2018 7:35:01 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentOutcomeVersion generated by hbm2java
 */
@Entity
@Table(name = "student_outcome_version", catalog = "test")
public class StudentOutcomeVersion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer studentOutcomeVersionId;
	private EducationalProgram educationalProgram;
	private String studentOutcomeVersionCode;
	private Date studentOutcomeVersionDate;
	private boolean studentOutcomeVersionIsused;
	private Set<PeoSoMapVersion> peoSoMapVersions = new HashSet<PeoSoMapVersion>(0);
	private Set<CoSoMapVersion> coSoMapVersions = new HashSet<CoSoMapVersion>(0);
	private Set<StudentOutcome> studentOutcomes = new HashSet<StudentOutcome>(0);
	private Set<CoSoMapVersion> coSoMapVersions_1 = new HashSet<CoSoMapVersion>(0);
	private Set<StudentOutcome> studentOutcomes_1 = new HashSet<StudentOutcome>(0);
	private Set<PeoSoMapVersion> peoSoMapVersions_1 = new HashSet<PeoSoMapVersion>(0);

	public StudentOutcomeVersion() {
	}

	public StudentOutcomeVersion(String studentOutcomeVersionCode, Date studentOutcomeVersionDate,
			boolean studentOutcomeVersionIsused) {
		this.studentOutcomeVersionCode = studentOutcomeVersionCode;
		this.studentOutcomeVersionDate = studentOutcomeVersionDate;
		this.studentOutcomeVersionIsused = studentOutcomeVersionIsused;
	}

	public StudentOutcomeVersion(EducationalProgram educationalProgram, String studentOutcomeVersionCode,
			Date studentOutcomeVersionDate, boolean studentOutcomeVersionIsused, Set<PeoSoMapVersion> peoSoMapVersions,
			Set<CoSoMapVersion> coSoMapVersions, Set<StudentOutcome> studentOutcomes,
			Set<CoSoMapVersion> coSoMapVersions_1, Set<StudentOutcome> studentOutcomes_1,
			Set<PeoSoMapVersion> peoSoMapVersions_1) {
		this.educationalProgram = educationalProgram;
		this.studentOutcomeVersionCode = studentOutcomeVersionCode;
		this.studentOutcomeVersionDate = studentOutcomeVersionDate;
		this.studentOutcomeVersionIsused = studentOutcomeVersionIsused;
		this.peoSoMapVersions = peoSoMapVersions;
		this.coSoMapVersions = coSoMapVersions;
		this.studentOutcomes = studentOutcomes;
		this.coSoMapVersions_1 = coSoMapVersions_1;
		this.studentOutcomes_1 = studentOutcomes_1;
		this.peoSoMapVersions_1 = peoSoMapVersions_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_outcome_version_id", unique = true, nullable = false)
	public Integer getStudentOutcomeVersionId() {
		return this.studentOutcomeVersionId;
	}

	public void setStudentOutcomeVersionId(Integer studentOutcomeVersionId) {
		this.studentOutcomeVersionId = studentOutcomeVersionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "edu_program_id")
	public EducationalProgram getEducationalProgram() {
		return this.educationalProgram;
	}

	public void setEducationalProgram(EducationalProgram educationalProgram) {
		this.educationalProgram = educationalProgram;
	}

	@Column(name = "student_outcome_version_code", nullable = false, length = 10)
	public String getStudentOutcomeVersionCode() {
		return this.studentOutcomeVersionCode;
	}

	public void setStudentOutcomeVersionCode(String studentOutcomeVersionCode) {
		this.studentOutcomeVersionCode = studentOutcomeVersionCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "student_outcome_version_date", nullable = false, length = 10)
	public Date getStudentOutcomeVersionDate() {
		return this.studentOutcomeVersionDate;
	}

	public void setStudentOutcomeVersionDate(Date studentOutcomeVersionDate) {
		this.studentOutcomeVersionDate = studentOutcomeVersionDate;
	}

	@Column(name = "student_outcome_version_isused", nullable = false)
	public boolean isStudentOutcomeVersionIsused() {
		return this.studentOutcomeVersionIsused;
	}

	public void setStudentOutcomeVersionIsused(boolean studentOutcomeVersionIsused) {
		this.studentOutcomeVersionIsused = studentOutcomeVersionIsused;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeVersion")
	public Set<PeoSoMapVersion> getPeoSoMapVersions() {
		return this.peoSoMapVersions;
	}

	public void setPeoSoMapVersions(Set<PeoSoMapVersion> peoSoMapVersions) {
		this.peoSoMapVersions = peoSoMapVersions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeVersion")
	public Set<CoSoMapVersion> getCoSoMapVersions() {
		return this.coSoMapVersions;
	}

	public void setCoSoMapVersions(Set<CoSoMapVersion> coSoMapVersions) {
		this.coSoMapVersions = coSoMapVersions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeVersion")
	public Set<StudentOutcome> getStudentOutcomes() {
		return this.studentOutcomes;
	}

	public void setStudentOutcomes(Set<StudentOutcome> studentOutcomes) {
		this.studentOutcomes = studentOutcomes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeVersion")
	public Set<CoSoMapVersion> getCoSoMapVersions_1() {
		return this.coSoMapVersions_1;
	}

	public void setCoSoMapVersions_1(Set<CoSoMapVersion> coSoMapVersions_1) {
		this.coSoMapVersions_1 = coSoMapVersions_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeVersion")
	public Set<StudentOutcome> getStudentOutcomes_1() {
		return this.studentOutcomes_1;
	}

	public void setStudentOutcomes_1(Set<StudentOutcome> studentOutcomes_1) {
		this.studentOutcomes_1 = studentOutcomes_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeVersion")
	public Set<PeoSoMapVersion> getPeoSoMapVersions_1() {
		return this.peoSoMapVersions_1;
	}

	public void setPeoSoMapVersions_1(Set<PeoSoMapVersion> peoSoMapVersions_1) {
		this.peoSoMapVersions_1 = peoSoMapVersions_1;
	}

}
