package com.yuen.domain;
// Generated Jan 30, 2018 7:35:01 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestReviewerDecision generated by hbm2java
 */
@Entity
@Table(name = "test_reviewer_decision", catalog = "test")
public class TestReviewerDecision implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer testReviewerDecisionId;
	private byte testReviewerDecisionCode;
	private String testReviewerDecisionDesc;
	private boolean testReviewerDecisionFortest;
	private Set<TestComment> testComments = new HashSet<TestComment>(0);
	private Set<QuestionComment> questionComments = new HashSet<QuestionComment>(0);
	private Set<TestComment> testComments_1 = new HashSet<TestComment>(0);
	private Set<QuestionComment> questionComments_1 = new HashSet<QuestionComment>(0);

	public TestReviewerDecision() {
	}

	public TestReviewerDecision(byte testReviewerDecisionCode, String testReviewerDecisionDesc,
			boolean testReviewerDecisionFortest) {
		this.testReviewerDecisionCode = testReviewerDecisionCode;
		this.testReviewerDecisionDesc = testReviewerDecisionDesc;
		this.testReviewerDecisionFortest = testReviewerDecisionFortest;
	}

	public TestReviewerDecision(byte testReviewerDecisionCode, String testReviewerDecisionDesc,
			boolean testReviewerDecisionFortest, Set<TestComment> testComments, Set<QuestionComment> questionComments,
			Set<TestComment> testComments_1, Set<QuestionComment> questionComments_1) {
		this.testReviewerDecisionCode = testReviewerDecisionCode;
		this.testReviewerDecisionDesc = testReviewerDecisionDesc;
		this.testReviewerDecisionFortest = testReviewerDecisionFortest;
		this.testComments = testComments;
		this.questionComments = questionComments;
		this.testComments_1 = testComments_1;
		this.questionComments_1 = questionComments_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "test_reviewer_decision_id", unique = true, nullable = false)
	public Integer getTestReviewerDecisionId() {
		return this.testReviewerDecisionId;
	}

	public void setTestReviewerDecisionId(Integer testReviewerDecisionId) {
		this.testReviewerDecisionId = testReviewerDecisionId;
	}

	@Column(name = "test_reviewer_decision_code", nullable = false)
	public byte getTestReviewerDecisionCode() {
		return this.testReviewerDecisionCode;
	}

	public void setTestReviewerDecisionCode(byte testReviewerDecisionCode) {
		this.testReviewerDecisionCode = testReviewerDecisionCode;
	}

	@Column(name = "test_reviewer_decision_desc", nullable = false, length = 65535)
	public String getTestReviewerDecisionDesc() {
		return this.testReviewerDecisionDesc;
	}

	public void setTestReviewerDecisionDesc(String testReviewerDecisionDesc) {
		this.testReviewerDecisionDesc = testReviewerDecisionDesc;
	}

	@Column(name = "test_reviewer_decision_fortest", nullable = false)
	public boolean isTestReviewerDecisionFortest() {
		return this.testReviewerDecisionFortest;
	}

	public void setTestReviewerDecisionFortest(boolean testReviewerDecisionFortest) {
		this.testReviewerDecisionFortest = testReviewerDecisionFortest;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testReviewerDecision")
	public Set<TestComment> getTestComments() {
		return this.testComments;
	}

	public void setTestComments(Set<TestComment> testComments) {
		this.testComments = testComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testReviewerDecision")
	public Set<QuestionComment> getQuestionComments() {
		return this.questionComments;
	}

	public void setQuestionComments(Set<QuestionComment> questionComments) {
		this.questionComments = questionComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testReviewerDecision")
	public Set<TestComment> getTestComments_1() {
		return this.testComments_1;
	}

	public void setTestComments_1(Set<TestComment> testComments_1) {
		this.testComments_1 = testComments_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testReviewerDecision")
	public Set<QuestionComment> getQuestionComments_1() {
		return this.questionComments_1;
	}

	public void setQuestionComments_1(Set<QuestionComment> questionComments_1) {
		this.questionComments_1 = questionComments_1;
	}

}
